---
- name: Prześlij plik z pulpitu na MikroTik
  hosts: all
  gather_facts: false

  vars:
    local_file: "C:\Users\Intero\Desktop\testwiedzyoniczym.txt"
    router_ip: "10.10.11.178"
    remote_path: "/testwiedzyoniczym.txt"

  tasks:
    - name: Kopiowanie pliku na router
      ansible.builtin.shell: |
        scp "{{ local_file }}" user@{{ router_ip }}:{{ remote_path }}
      args:
        executable: /bin/bash
