---
- name: Tescik przez SSH
  hosts: all
  gather_facts: no
  tasks:
    - name: Pokaz zasoby systemowe
      ansible.netcommon.cli_command:
        command: [:put [/system package get [find name="routeros"] version]]
      register: wynik

    - name: Pokaz wynik w konsoli AWX
      ansible.builtin.debug:
        var: wynik.stdout_lines
