---
- name: Wyslij plik na MikroTik
  hosts: all
  gather_facts: false

  vars:
    local_file: "C:/Users/Intero/Desktop/testwiedzoniczym.txt"
    router_ip: "10.10.11.169"
    remote_path: "/testwiedzoniczym.txt"
    router_user: "admin"

  tasks:
    - name: Kopiowanie pliku przez SCP
      ansible.builtin.shell: |
        scp "{{ local_file }}" {{ router_user }}@{{ router_ip }}:{{ remote_path }}
