---
- name: Konfiguracja uzytkownikow i kluczy SSH na MikroTik
  gather_facts: false
  hosts: all
  connection: network_cli

  vars:
    ssh_public_key_string: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBXJgJRptFTu+uux3fdl4IlYye/6zHUYUM1gx+ekjxR7 test"

  tasks:
    - name: Przygotowanie pliku klucza (czyszczenie i zapis)
      community.routeros.command:
        commands:
          - /file remove [find name="ansible_key.pub.txt"]
          - /file print file=ansible_key.pub
      failed_when: false # Ignorujemy błąd, jeśli plik do usunięcia nie istniał

    - name: Odczekanie chwili na wygenerowanie pliku
      ansible.builtin.pause:
        seconds: 2

    - name: Wpisanie zawartosci do pliku klucza
      community.routeros.command:
        commands:
          - /file set ansible_key.pub.txt contents="{{ ssh_public_key_string }}"

    - name: Bezpieczne dodanie uzytkownikow (tylko jesli nie istnieja)
      community.routeros.command:
        commands:
          - :if ([:len [/user find name="user_full"]] = 0) do={ /user add name="user_full" group="full" comment="Konto FULL" password="LosoweSkomplikowaneHaslo123!" }
          - :if ([:len [/user find name="user_write"]] = 0) do={ /user add name="user_write" group="write" comment="Konto WRITE" password="LosoweSkomplikowaneHaslo123!" }
          - :if ([:len [/user find name="user_read"]] = 0) do={ /user add name="user_read" group="read" comment="Konto READ" password="LosoweSkomplikowaneHaslo123!" }

    - name: Import kluczy SSH dla uzytkownikow
      community.routeros.command:
        commands:
          - /user ssh-keys import user="user_full" public-key-file="ansible_key.pub.txt"
          - /user ssh-keys import user="user_write" public-key-file="ansible_key.pub.txt"
          - /user ssh-keys import user="user_read" public-key-file="ansible_key.pub.txt"

    - name: Sprzatanie pliku klucza
      community.routeros.command:
        commands:
          - /file remove [find name="ansible_key.pub.txt"]
      failed_when: false
