---
- name: Konfiguracja uzytkownikow i kluczy SSH na MikroTik
  gather_facts: false
  hosts: all
  connection: network_cli

  vars:
    ssh_public_key_string: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBXJgJRptFTu+uux3fdl4IlYye/6zHUYUM1gx+ekjxR7 test"

  tasks:
    - name: Przygotowanie pliku z kluczem SSH
      community.routeros.command:
        commands:
          # Czyścimy stary plik (jeśli jest) i tworzymy nowy w JEDNYM kroku
          - :do { /file remove [find name="ansible_key.pub"] } on-error={}; /file print file=ansible_key.pub; :delay 1s; /file set ansible_key.pub contents="{{ ssh_public_key_string }}"

    - name: Stworzenie uzytkownikow i import kluczy
      community.routeros.command:
        commands:
          # Użytkownik FULL
          - :do { /user add name="user_full" group="full" comment="Konto FULL" } on-error={}
          - /user ssh-keys import user="user_full" public-key-file="ansible_key.pub"
          
          # Użytkownik WRITE
          - :do { /user add name="user_write" group="write" comment="Konto WRITE" } on-error={}
          - /user ssh-keys import user="user_write" public-key-file="ansible_key.pub"
          
          # Użytkownik READ
          - :do { /user add name="user_read" group="read" comment="Konto READ" } on-error={}
          - /user ssh-keys import user="user_read" public-key-file="ansible_key.pub"

    - name: Sprzatanie po ekshumacji klucza
      community.routeros.command:
        commands:
          - /file remove [find name="ansible_key.pub"]
